---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  #- name: test
  #  image: golang:1.11
  #  commands:
  #  - go test -v ./...
  #  volumes:
  #  - name: gopath
  #    path: /go
  #  environment:
  #    http_proxy: http://10.1.1.46:8888
  #    https_proxy: http://10.1.1.46:8888


- name: build
  image: golang:1.11
  commands:
  - "go build -ldflags \"-extldflags \\\\\"-static\\\\\"\" -o release/linux/amd64/drone-server github.com/drone/drone/cmd/drone-server"
  - CGO_ENABLED=0 go build -o release/linux/amd64/drone-agent github.com/drone/drone/cmd/drone-agent
  - CGO_ENABLED=0 go build -o release/linux/amd64/drone-controller github.com/drone/drone/cmd/drone-controller
  volumes:
  - name: gopath
    path: /go
  environment:
    http_proxy: http://10.1.1.46:8888
    https_proxy: http://10.1.1.46:8888
  when:
    event:
    - push
    - tag

- name: publish_agent
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.agent.linux.amd64
    repo: registry.kuainiujinke.com/drone/agent
    password: Zxcvbnm,.1
    username: zhangpanpan
    registry: registry.kuainiujinke.com
  when:
    event:
    - push
    - tag

- name: publish_controller
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.controller.linux.amd64
    repo: registry.kuainiujinke.com/drone/controller
    password: Zxcvbnm,.1
    username: zhangpanpan
    registry: registry.kuainiujinke.com
  when:
    event:
    - push
    - tag

- name: publish_server
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.server.linux.amd64
    repo: registry.kuainiujinke.com/drone/drone
    password: Zxcvbnm,.1
    username: zhangpanpan
    registry: registry.kuainiujinke.com
  when:
    event:
    - push
    - tag

volumes:
- name: gopath
  temp: {}

